name: Fetch Athenry Weather Data

on:
  schedule:
    - cron: "0 10 * * *"          # Run daily at 10am UTC
  workflow_dispatch:              # Allow manual triggering

jobs:
  run-weather-script:
    runs-on: ubuntu-latest        # Use a Linux VM (Ubuntu)

    permissions:
      contents: write  
    
    env:
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

    steps:
      # 1 Clone the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 1.1 Debug step to verify environment variables
      - name: Debug Environment Variables
        run: |
          echo "SMTP_SERVER=$SMTP_SERVER"
          echo "SMTP_PORT=$SMTP_PORT"
          echo "SENDER_EMAIL=$SENDER_EMAIL"
          echo "RECIPIENT_EMAIL=$RECIPIENT_EMAIL"

      # 2 Install python and dependencies so that send_error_email.py can run
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x" 

      - name: Install Python Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3 Make weather.sh executable
      - name: Make weather.sh executable
        run: chmod +x weather.sh

      # 4 Run the weather.sh script
      - name: Run Weather Script
        run: ./weather.sh

      # 5 Configure Git for pushing changes
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 6 Commit and push
      - name: Commit and Push Changes
        run: |
          git add data/weather/
          git add weather.log
          git commit -m "Athenry weather data automated update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
