name: Automate Weather Data Collection

# Define events to trigger the workflow
on:
  # Schedule the workflow to run daily at 10 AM UTC
  schedule:
    - cron: "0 10 * * *"

  # Allow manual triggering of the workflow
  workflow_dispatch:

# Define the jobs
jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    # Environment variables for the script
    env:
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set execute permissions for weather.sh
      - name: Make weather.sh executable
        run: chmod +x weather.sh

      # Run the weather.sh script
      - name: Run Weather Script
        run: ./weather.sh

      # Configure Git for pushing new data
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Stage, commit, and push changes
      - name: Commit and Push Changes
        run: |
          git add data/weather/
          git commit -m "Automated weather data update"
          git push
        env:
          # Use GitHub token to authenticate
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}